### ISSUE TITLE
:P 我这是找到了什么

### ISSUE THREAD

**Issue by Thexiaoyuqaq** [STrance13/sky.strance13.github.io#1]
,支持一些（doge

**Comment by STrance13** [comment]
哈哈哈感谢您的star，这个是曾经的html5课程的大作业啦UwU。当初想着我写了这么久不得发出来（虽然代码很是拙劣），最近也是准备改进（实际上是发现之前上传少了东西且本地已经丢失了（悲））。

**Comment by Thexiaoyuqaq** [comment]
哈哈哈，重新写吧，主要是你写的看出来你的努力了，然后正好搜到了你的项目网页，顺藤摸瓜找到了，重写比优化更有性价比（doge，

**Comment by STrance13** [comment]
也确实有重写的想法，但这一版也是想把缺失的部分补齐（虽然没什么东西）。html5要深入学习的地方真的好多哇:'(
顺带一提，这个也能先搜到网页再搜到库的吗？还是说被什么搜索引擎给爬了UwU

**Comment by Thexiaoyuqaq** [comment]
bing爬了

**Comment by Thexiaoyuqaq** [comment]
哎哟我去，我上面原来有错别字（

**Comment by STrance13** [comment]
原来如此´_>`

**Comment by Thexiaoyuqaq** [comment]
有观察我的Bot代码吗(doge
评价评价

**Comment by STrance13** [comment]
这几天在考试没看-_-
但是bot方面我只是略有涉猎，还是没多少水平评价的´_>`
